### ISSUE TITLE
Does this can deal with mutiple genomes?

### ISSUE THREAD

**Issue by bioinformaticspcj** [smortezah/smashpp#1]
Dear the authors,
Thanks for devoloping the useful program. I have a question that does this  software can deal with mutiple genomes ? We just want to find the rearrangements accross 10 genomes and how should I do?
Thanks again and looking forward to your reply.

**Comment by pratas** [comment]
Dears,

smashpp is for pairwise comparison, which means that it receives as input two genomic sequences [with any size]. Therefore, in your case you need to perform analysis between pairs within the 10 genomes. Consider that you have G1, G2, ..., G10 -> if you run G1 vs G2, G2 vs G3, G3 vs G4, ... G9 vs G10, you may have indication of the rearrangements present. Note that this is not the same as running all with all, which makes it clear but with a quadratic complexity and, hence, you will need more computational time.

smashpp can be optimized to the nature of the genomes. So, if you provide more information on it, we can optimize your case:
* Which kind of genomic sequences are in the analysis? Viruses? Bacteria?
* What are the sizes of the 10 sequences?
* Are them already assembled?
