### ISSUE TITLE
Paired_end sequence

### ISSUE THREAD

**Issue by MingchenInSZ** [smortezah/smashpp#10]
I am working with a pairs of sequences in PE model, and I want to find the rerangements. How to process such data with your tool？
Thanks a lot!

**Comment by pratas** [comment]
Dear,

the smashpp does not work directly from the FASTQ reads but instead from the FASTA assembled sequences.
Before the use of smashpp for the mentioned application, there is the need to assemble these sequences which the methodology is dependent on the organisms and sequencing protocols that have been used.
After the assembly, if you have any doubts on how to use smashpp, please let us know.

Best regards,
Diogo
