### ISSUE TITLE
conda installed smashpp crashes

### ISSUE THREAD

**Issue by aldertzomer** [smortezah/smashpp#11]
This is using the latest conda with python 3.9

lp0105:~$ smashpp
Illegal instruction (core dumped)

in dmesg:
[26008400.796227] traps: smashpp[613] trap invalid opcode ip:55e5e5e0c9e3 sp:7ffc9a45b5c0 error:0 in smashpp[55e5e5e00000+9a000]

Not sure what the issue is.

**Comment by smortezah** [comment]
> This is using the latest conda with python 3.9
> 
> lp0105:~$ smashpp Illegal instruction (core dumped)
> 
> in dmesg: [26008400.796227] traps: smashpp[613] trap invalid opcode ip:55e5e5e0c9e3 sp:7ffc9a45b5c0 error:0 in smashpp[55e5e5e00000+9a000]
> 
> Not sure what the issue is.

What's your operating system?

**Comment by IdoBar** [comment]
Same issue here on CentOS Linux release 7.4.1708 (Core)

**Comment by aldertzomer** [comment]
It works on an ubuntu 20 system, but not on an older ubuntu 16 system. I assume it's the newer c++ libraries which are not installed in the conda package.

**Comment by smortezah** [comment]
> Same issue here on CentOS Linux release 7.4.1708 (Core)

For older CentOS versions, you can download and unzip the ZIP file of smashpp (https://github.com/smortezah/smashpp/archive/refs/heads/master.zip). Then install the following requirements:
- git and make:
  - `yum install -y git make`
- cmake3:
  - `yum install -y epel-release cmake3`
  - `yum ln -s /usr/bin/cmake3 /usr/bin/cmake`
- gcc and g++:
  - `yum install -y centos-release-scl`
  - `yum install -y devtoolset-11-gcc devtoolset-11-gcc-c++`
  - `scl enable devtoolset-11 -- bash`

Finally go to the smashpp folder and install it:
- `cd smashpp`
- `bash install.sh`

**Comment by smortezah** [comment]
> It works on an ubuntu 20 system, but not on an older ubuntu 16 system. I assume it's the newer c++ libraries which are not installed in the conda package.

It's because of the old g++ library.

You can download and unzip the ZIP file of smashpp (https://github.com/smortezah/smashpp/archive/refs/heads/master.zip). Then install the following requirements:
- git and cmake:
  - `sudo apt update && apt install -y git cmake`
- gcc and g++ version 9:
  - `sudo apt-get install -y software-properties-common`
  -  `sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
  - `sudo apt-get update`
  - `sudo apt-get install -y gcc-9 g++-9`
  - `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9`

Finally go to the smashpp folder and install it:
 - `cd smashpp`
- `bash install.sh`

In Ubuntu 20, you could easily install g++ by `sudo apt install -y g++`.

Conda package will be updated later.

**Comment by IdoBar** [comment]
I could get it to run after installing `gxx_linux-64`, `gcc` and `cmake` in conda and then compiling the executable from the repository.

**Comment by plaquette** [comment]
> > It works on an ubuntu 20 system, but not on an older ubuntu 16 system. I assume it's the newer c++ libraries which are not installed in the conda package.
> 
> It's because of the old g++ library.
> 
> You can download and unzip the ZIP file of smashpp (https://github.com/smortezah/smashpp/archive/refs/heads/master.zip). Then install the following requirements:
> 
> * git and cmake:
>   
>   * `sudo apt update && apt install -y git cmake`
> * gcc and g++ version 9:
>   
>   * `sudo apt-get install -y software-properties-common`
>   * `sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
>   * `sudo apt-get update`
>   * `sudo apt-get install -y gcc-9 g++-9`
>   * `sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9`
> 
> Finally go to the smashpp folder and install it:
> 
> * `cd smashpp`
> * `bash install.sh`
> 
> Note: in Ubuntu 20, you could easily install g++ by `sudo apt install -y g++`.
> 
> Conda package will be updated later.

was the conda package updated?

i still get this error if using this legacy version via conda.
