### ISSUE TITLE
Errors generated during Installation on M1 MacBookPro 

### ISSUE THREAD

**Issue by duavang** [smortezah/smashpp#12]
Hi, I keep getting the following message when I try to install: 

2 errors generated.
make[2]: *** [CMakeFiles/smashpp.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/smashpp.dir/all] Error 2
make: *** [all] Error 2

Any suggestions on how to resolve this?

**Comment by smortezah** [comment]
It should work now on the ZIP file of the project (https://github.com/smortezah/smashpp/archive/refs/heads/master.zip) or when it's cloned.

Conda package will be updated later.
