### ISSUE TITLE
Segmentation fault during reference-free compression

### ISSUE THREAD

**Issue by mmleger** [smortezah/smashpp#14]
Hi, I'm trying to run smash++ on a Mac (10.15.7, installed using homebrew), on two fairly small, fairly fragmented eukaryotic genomes (around 24MB each, 287 contigs and 501 contigs respectively, N50 180.5kb for the first one).

The test run I did using the ref and tar files in example/ worked fine, but with my two genomes I get a segmentation fault during the  Ref-free compression of segment 4 (or in one case, which I haven't been able to replicate, segment 5). This happens regardless of whether I specify any options, or different values of -m or -l. The output files in all cases include .seq files for both genomes, and a series of sequentially labelled files named 0.genome1.fasta.genome2.fasta.s[number]

Is this likely to be a problem with the command/parameters I'm using, or a property of my data, or of my system? Thanks!

**Comment by smortezah** [comment]
Resolved. Please update smash++ to the new version.
