### ISSUE TITLE
[Question] interpreting smashpp output files

### ISSUE THREAD

**Issue by plaquette** [smortezah/smashpp#17]
Hey @smortezah ,

i have troubles understanding the smashpp's output - if it produces an output file of the form:

```Json
{
    "watermark": "##SMASH++",
    "parameters": "<-r refrence.fa -t target.fa>",
    "reference": "refrence.fa",
    "reference_size": "1653432",
    "target": "target.fa",
    "target_size": "1016",
    "positions": [
        {
            "reference_begin": "321300",
            "reference_end": "322200",
            "reference_relative_redundancy": "0.7155",
            "reference_redundancy": "2.0000",
            "target_begin": "1016",
            "target_end": "180",
            "target_relative_redundancy": "0.6232",
            "target_redundancy": "2.0000",
            "inverted": "T",
        }
    ]
}
```

which corresponds to a target sequence of length 1000 like this:

```fasta
>target
ATGAATCCAAATCAAATACTTGAAAATTTAAAAAAAGAATTAAGTGAAAACGAATACGAAAATTATATCGCTATCTTAAAATTTAACGAAAAACAAAGCAAAGCAGATTTTCTAGTCTTTAACGCTCCTAATGAGCTTTTAGCCAAATTCATACAAACAAAATACGGTAAAAAAATTTCACATTTTTATGAAGTACAAAGCGGAAATAAAGCGAGCGTTTTGATACAAGCACAAAGCCAAAAACATAGTAGCAAAAGCACTAAAATCGATATCGCTCACATCAAGGCGCAAAGTACGATTTTAAATCCTTCTTTTACTTTTGAAAGCTTTGTAGTGGGGGATTCTAACAAATACGCTTATGGAGCTTGTAAAGCTATCTCACAAAAAGACAAACTGGGAAAACTTTATAATCCTATCTTTATCTATGGGCCTACAGGGCTTGGAAAAACGCACTTGCTTCAAGCTGTGGGAAATGCAAGTTTGGAAATGGGAAAAAAAGTGATTTATGCTACGAGTGAAAATTTTATCAATGATTTTACTTCAAATTTAAAAAATGGCTCTTTAGATAAATTTCACGAAAAATATAGAAATTGTGATGTTTTACTCATAGATGATGTGCAATTTTTAGGAAAAACAGACAAAATTCAAGAAGAGTTTTTCTTTATATTTAATGAGATTAAAAATAATGATGGGCAAATTATCATGACAAGTGATAACCCACCCAATATGCTAAAAGGTATCACCGAACGCTTAAAAAGTCGTTTTGCTCATGGTATCATAGCAGATATCACTCCACCTCAACTGGATACAAAAATAGCCATCATACGCAAAAAATGCGAATTTAATGATATCAATCTTTCTAATGATATCATTAATTATATCGCCACTTCTTTAGGGGATAATATAAGAGAAATAGAAGGTATCATCATAAGCTTAAATGCTTATGCTAACATACTTGGACAAGAAATCACCCTTGAGCTAGCAAAAAGCGTGATGAAAG
```

could you help me understand where the fields "target_begin" and "target_end" point to?

it confuses me, that the begin is greater than the length of the sequence.

how can i convert the mentioned fields into actual coordinates of the target-sequence?

what i currently do is

```python

from Bio import SeqIO
    target_start = int(seq_dict["target_begin"])
    target_end = int(seq_dict["target_end"])

    reference_start = int(seq_dict["reference_begin"])
    reference_end = int(seq_dict["reference_end"])

    if target_start > target_end:
        target_start, target_end = target_end, target_start

    inverted = seq_dict["inverted"] == "T"

    assert target_start < target_end

    target_subseq = target_seq[target_start:target_end]
    reference_subseq = reference_seq[reference_start:reference_end]


    if inverted:       
        target_subseq = target_subseq.reverse_complement(id=target_seq.id, name=target_seq.name, description=target_seq.description)
```

but the resulting subsequences don't seem to make sense...
it seem like the header of both the target.fasta and refrence.fasta shift the positions (if i change the headers it returns different outputs) in the sequences...

can you help me sort out the actual sequences that were found by the smash-tool?

thank you!

**Comment by smortezah** [comment]
Hi @plaquette,

- **"target_size": "1016"** shows that the target sequence is 1016 base long, not 1000.
- **"inverted": "T"** shows there is inverted repeats; that's why the target_begin, 1016, is greater than the target_end, 180.
- The reference subsequence is 322200-321300+1=901 base long, and the target subsequence is 1016-180+1=837 base long.

What are the exact reference and target sequences, if they can be public?

**Comment by plaquette** [comment]
Hey @smortezah - thanks for your answer.

i'am confused to be honest.

if i run smash against some test fastas and i change the headers - the target_size shifts.
at least in my testing, it seems it takes the header into account as well since, if i count the sequence its exactly 1000bases and not 1016. and the additional 16 changes depending on the signs in the header.

to address this, i added a line of code in my pipeline that cuts off the header - this way it works as its supposed to.

i can give you an example (without headers - since i deleted the rest) but i don't know how useful this would be.

**Comment by smortezah** [comment]
Correct. The output positions are real positions of the input files, e.g. FASTA. So, the headers matter for the positions shown. This way, you can easily open the input FASTA file in your script, then read from the positions of the file that are calculated by Smash++. Although, there is the option "-ss" to save all the segments detected by the program, it usually produces intermediate segments that are not useful in the final calculations. We should solve this in the future version.

Note that, the contents of headers in e.g. FASTA files are, obviously, not involved in calculating similarities.

**Comment by plaquette** [comment]
thank you
