### ISSUE TITLE
Input files are deleted

### ISSUE THREAD

**Issue by hoelzer** [smortezah/smashpp#4]
I just installed smashpp via conda and executed:

```bash
smashpp -r ../2020-05-22_annotation/ontOnly_flye/01-Assembly/foo.fasta -t ../2020-05-22_annotation/hybrid_flye_pilon/01-Assembly/fii.fasta -n 6
```

that reported 
```
(smashpp) ➜     
====[ PREPARE DATA ]==================================
[+] foo.fasta (FASTA) -> foo.seq (seq) finished.
[+] fii.fasta (FASTA) -> fii.seq (seq) finished.

====[ REGULAR MODE ]==================================
[+] Creating model of foo.fasta done.
[+] Filtering fii.fasta done => 11 segments
[+] Ref-free compression of all segments done.         
[+] Repeating above process for all segments done.

====[ INVERTED MODE ]=================================
[+] Creating model of foo.fasta done.
[+] Filtering fii.fasta done => 0 segments

Error: the file
"../2020-05-22_annotation/ontOnly_flye/01-Assembly/foo.fasta"
cannot be opened or is empty.
```

and then deleted my input files `foo.fasta` and `fii.fasta`! 

It works when I run the same command directly on the two files by first copying them to the folder where I execute smashpp. 

That's a dangerous bug!

**Comment by awesomedeer** [comment]
Hi!
I think you can use `-sb                = save sequence (input: FASTA/FASTQ)` to avoid this.

Song

**Comment by hoelzer** [comment]
Hi, thanks for the hint. To reproduce this I did:

```
smashpp -r ../hybrid_flye_pilon_polished_masked.fasta \
-t ../ontOnly_flye_polished_masked.fasta -n 6
```
and my input files were again deleted:

```
Error: the file "../hybrid_flye_pilon_polished_masked.fasta"
cannot be opened or is empty.
```

followed by

```
smashpp -r ../hybrid_flye_pilon_polished_masked.fasta \
-t ../ontOnly_flye_polished_masked.fasta -n 6 -sb
```

that worked!

But anyway: deleting my input sequences in the first instance is not really an expected behavior.  And that the user needs to add a parameter to avoid deletion of his input files is... strange ;)

**Comment by awesomedeer** [comment]
Yes..I agree with you, so it's wothywhile reading through the help page.
Anyway, it's still a new software and need some time to grow up.

**Comment by hoelzer** [comment]
Of course! And that's why GitHub issues are here. ;) 

Surely my bug report should not be an accusation either. It might only interest potential new users that in certain cases the new software can delete sequences that have been assembled for days.

**Comment by smortezah** [comment]
@hoelzer thanks for the report.
Now, input files will never be removed. Also, in case of using "-sb", the ".seq" sequences will be saved in the current directory.
