### ISSUE TITLE
No output for small bacterial genomes

### ISSUE THREAD

**Issue by hoelzer** [smortezah/smashpp#5]
Hi!

I am trying to visualize rearrangements for two small bacterial genomes (~ 1Mbp). But even while tweaking the parameters a little bit (`-m`, `-l`, ...) I don't get any output:

```
(smashpp) ➜  smashpp smashpp -r 14-2711_R47.fasta -t Chlamydia_psittaci_6BC.fasta
====[ PREPARE DATA ]==================================
[+] 14-2711_R47.fasta (FASTA) -> 14-2711_R47.seq (seq) finished.
[+] Chlamydia_psittaci_6BC.fasta (FASTA) -> Chlamydia_psittaci_6BC.seq (seq) finished.

====[ REGULAR MODE ]==================================
[+] Creating model of 14-2711_R47.fasta done.
[+] Filtering Chlamydia_psittaci_6BC.fasta done => 0 segments

====[ INVERTED MODE ]=================================
[+] Creating model of 14-2711_R47.fasta done.
[+] Filtering Chlamydia_psittaci_6BC.fasta done => 0 segments

Total time: 3 sec.
```

So it seems Smashpp does not find any fragments/rearragnements between the two? 

This is how a MAUVE output for the same sequences looks like:
![Screenshot from 2020-05-25 10-43-09](https://user-images.githubusercontent.com/14393703/82795943-07f3c580-9e75-11ea-9e1b-24c970f8b505.png)

Maybe I am not using the parameters correctly?

**Comment by pratas** [comment]
Dear Martin,

I am sorry for the late answer.
I think it is just a matter of optimizing the parameters.
If you want and you can share these files, I will optimize these parameters for you.

Best regards,
Diogo

**Comment by kattruels** [comment]
Hi! 

I am having the same issue with E. coli genomes. Similarly, they show up in Mauve. Any suggestion of optimal segment length for a 4.5 Mb chromosome? I'll try several options... I'll report back if I find it!

**Comment by pratas** [comment]
Hi Kat,

can you please provide the IDs or sequences?
If they are private, alternatively, please try: 

conda install -c bioconda smashpp -y
smashpp -v -nr -ft 0 -rm 16,0,0.1,0.95/7,0,0.1,0.95 -f 20000 -d 1 -m 500 -th 1.5 -r ECOLI_1.fa -t ECOLI_2.fa
smashpp -viz -nrr -nr -m 500 -o ECOLI_1.fa.ECOLI_2.svg ECOLI_1.fa.ECOLI_2.fa.pos

Assuming ECOLI_1.fa and ECOLI_2.fa are the sequences.
It is a matter of optimization...

Best regards,
Diogo
