### ISSUE TITLE
About the multiple threads

### ISSUE THREAD

**Issue by awesomedeer** [smortezah/smashpp#6]
Hi Morteza!
I really like smash++. The figures are amazing.
I have a question about `-tr` parameter. When I set it to >1 like 10 and 20 ,also defalut(4), it seems the software still use single thread. I have 30 cores in my server.

Song

**Comment by smortezah** [comment]
Dear Song,
Glad to hear that you liked the tool.
In the current version, only creating models can be done in multi-threaded fashion; therefore, most of the time (> 95%), the tool uses a single thread.

**Comment by awesomedeer** [comment]
Thank you! I have no question now.
