### ISSUE TITLE
WSL installation

### ISSUE THREAD

**Issue by drhoads** [smortezah/smashpp#7]
Trying to install in WSL on a Win10 64bit professional OS
dougrhoads@ARSC-GP50LH2:~$ git clone https://github.com/smortezah/smashpp.git
dougrhoads@ARSC-GP50LH2:~$ cd smashpp
dougrhoads@ARSC-GP50LH2:~/smashpp$ ./install.sh
-bash: ./install.sh: Permission denied
(base) dougrhoads@ARSC-GP50LH2:~/smashpp$ sudo ./install.sh
[sudo] password for dougrhoads:
sudo: ./install.sh: command not found

Any suggestions?

**Comment by drhoads** [comment]
Solved
#install smashpp
git clone https://github.com/smortezah/smashpp.git
cd smashpp
sudo bash install.sh
sudo cp smashpp /usr/local/bin/
cd ..
sudo rm -rf smashpp
#use smash++
cd /mnt/f/DNAwork/Snake
smashpp -n 8  -r Others/Cviridis.fna  -t Frozen/Chorridus.fasta
smashpp -viz -o Cviridis.Chorridus.svg Cviridis.Chorridus.pos

**Comment by smortezah** [comment]
Thanks for sharing your experience.

**Comment by drhoads** [comment]
I am a little confused on the parameter list.  I have the program running fine now, but it is not clear to me which parameter I use to set the k-mer, is it -f 14 to set k-mer 14?

[cid:image001.jpg@01D70F53.D9650EE0]

**Comment by smortezah** [comment]
The k-mer size can be set by "-rm" or "-tm" flags, under the name of "k" (context size), i.e. the first parameter. 

To have an idea of how to set other parameters in the mentioned flags, use "-ll" flag.
