### ISSUE TITLE
No output for two WGS analyzed...

### ISSUE THREAD

**Issue by frankMusacchia** [smortezah/smashpp#8]
Hi,
I am currently having no output for two human WGS 100x samples analyzed with smash++.
Can you tell me if there is some error or additional parameters I should use? 
Thanks

This is how I executed it:

1. Since I have Illumina fastq sequencing with paired end, there are two files instead of one needed in input by smash++. Thus, I am merging paired ends in a unique file with bwa-kit mergepe:

/projects/bin/bwa.kit/seqtk mergepe sample_R1.fastq.gz sample_R2.fastq.gz > PD-7107_S4.fastq

2. launching smash++ with default parameters from within a container:

singularity run  /projects/bin/SMASH++_container.sif /sw/smashpp/smashpp 
-r /projects/DATA/references/genome/Homo_sapiens_assembly38.fasta 
-t /projects/PD-7107_S4.fastq -n 20

3. launching smash++ with parameters:
singularity run  /projects/bin/SMASH++_container.sif /sw/smashpp/smashpp 
-r /projects/DATA/references/genome/Homo_sapiens_assembly38.fasta 
-t /projects/PD-7107_B.fastq -l 0 -m 1000 -n 20

**First LOG (2.):**

====[ PREPARE DATA ]==================================
[+] Homo_sapiens_assembly38.fasta (FASTA) -> Homo_sapiens_assembly38.seq (seq) finished.
[+] PD-7107_S4.fastq (FASTQ) -> PD-7107_S4.seq (seq) finished.

====[ REGULAR MODE ]==================================
[+] Creating model of Homo_sapiens_assembly38.fasta done.
[+] Filtering PD-7107_S4.fastq done => 8543 segments
[+] Ref-free compression of segment 14 ...
[+] Ref-free compression of segment 28 ...
....
[+] Ref-free compression of segment 8536 ...
[+] Ref-free compression of all segments done.         
[+] Repeating above process for segment 12 ... 
....
====[ PREPARE DATA ]==================================
[+] Homo_sapiens_assembly38.fasta (FASTA) -> Homo_sapiens_assembly38.seq (seq) finished.
[+] PD-7107_S4.fastq (FASTQ) -> PD-7107_S4.seq (seq) finished.

====[ REGULAR MODE ]==================================
[+] Creating model of Homo_sapiens_assembly38.fasta done.
[+] Filtering PD-7107_S4.fastq done => 8543 segments
[+] Ref-free compression of segment 14 ...
[+] Ref-free compression of segment 28 ...
...
[+] Ref-free compression of segment 8536 ...
[+] Ref-free compression of all segments done.         
[+] Repeating above process for segment 12 ... 
[+] Repeating above process for segment 25 ... 
...
[+] Repeating above process for segment 8534 ... 
[+] Repeating above process for all segments done.

====[ INVERTED MODE ]=================================
[+] Creating model of Homo_sapiens_assembly38.fasta done.
[+] Filtering PD-7107_S4.fastq done => 0 segments

Total time: 192:10:27 hour:min:sec.

**First OUTPUT FILE:**

[fmusacchia@me smash]$ more Homo_sapiens_assembly38.fasta.PD-7107_S4.fastq.pos
##SMASH++
##PARAM=<-r /projects//DATA/references/genome/Homo_sapiens_assembly38.fasta -t /projects/PD-7107_S4.fastq -n 20>
##INFO=<Ref=Homo_sapiens_assembly38.fasta,RefSize=3249912778,Tar=PD-7107_S4.fastq,TarSize=1031281362254>
#RBeg	REnd	RRelRdn	RRdn	TBeg	TEnd	TRelRdn	TRdn	Inv

_As you can see it took 192 hours but gave no results._

**Second LOG (3.)**

====[ PREPARE DATA ]==================================
[+] Homo_sapiens_assembly38.fasta (FASTA) -> Homo_sapiens_assembly38.seq (seq) finished.
[+] PD-7107_B.fastq (FASTQ) -> PD-7107_B.seq (seq) finished.

====[ REGULAR MODE ]==================================
[+] Creating model of Homo_sapiens_assembly38.fasta done.
[+] Filtering PD-7107_B.fastq done => 1057 segments
[+] Ref-free compression of segment 14 ...
[+] Ref-free compression of segment 28 ...
...
[+] Ref-free compression of segment 1051 ...
[+] Ref-free compression of all segments done.         
[+] Repeating above process for segment 12 ... 
...
[+] Repeating above process for segment 1055 ... 
[+] Repeating above process for all segments done.

====[ INVERTED MODE ]=================================
[+] Creating model of Homo_sapiens_assembly38.fasta done.
[+] Filtering PD-7107_B.fastq done => 1360 segments
[+] Ref-free compression of segment 14 ...
...
[+] Ref-free compression of segment 1348 ...
[+] Ref-free compression of all segments done.         
[+] Repeating above process for segment 12 ... 
[+] Repeating above process for segment 25 ... 
...
[+] Repeating above process for segment 1359 ... 
[+] Repeating above process for all segments done.

Total time: 110:38:21 hour:min:sec.

**Second OUTPUT:**

[fmusacchia@me smash]$ more Homo_sapiens_assembly38.fasta.PD-7107_B.fastq.pos
##SMASH++
##PARAM=<-r /projects//DATA/references/genome/Homo_sapiens_assembly38.fasta -t /projects/PD-7107_B.fastq -l 0 -m 1000 -n 20>
##INFO=<Ref=Homo_sapiens_assembly38.fasta,RefSize=3249912778,Tar=PD-7107_B.fastq,TarSize=935069756484>
#RBeg	REnd	RRelRdn	RRdn	TBeg	TEnd	TRelRdn	TRdn	Inv

**Comment by pratas** [comment]
Dear Frank,

I think smashpp is not completely prepared to handle FASTQ but rather FASTA only.
Perhaps assembling first the genome will work.
Perhaps the image is not generated because the minimal block size must be lower than the FASTQ read size (DNA sequence). For example, try 80.

Best regards,
Diogo

**Comment by frankMusacchia** [comment]
Thank you, Diogo, for your answer. I will let you know how it goes with 80. 
How do you usually assemble wgs for smashpp? Is Velvet good, for example,  or you suggest any other tool/pipeline?
Best regards 
Francesco

**Comment by pratas** [comment]
Dear Frank,

For assembling it depends on the genome type, sequencing process/protocol, and may other things. Assembling a genome for one type may not be necessary the best way to another purpose. For viral enriched genomes, we use TRACESPipe ( https://github.com/viromelab/tracespipe ). TRACESPipe combines both de-novo (metaSPAdes) and reference-based assembly (bowtie2) through iterative refinement for multi-organ sample purposes. However, if you want to assemble other types of genomes , for example humans or plants, you may want to check assemblers such as Hifiasm (there are many others) and combine sequencing long reads with short reads.

Best regards,
Diogo
